snap-cloud/snapcon

Gemfile.lock

Update shoulda-matchers to version 4.1.2

---

app/views/conferences/_header.haml

hide venue link if there is no venue link

---

app/controllers/admin/commercials_controller.rb
app/controllers/admin/venue_commercials_controller.rb
app/controllers/commercials_controller.rb
app/models/commercial.rb
app/views/admin/commercials/index.html.haml
app/views/admin/events/index.html.haml
app/views/admin/events/show.html.haml
app/views/admin/reports/_all_events.html.haml
app/views/admin/reports/_events_without_commercials.html.haml
app/views/admin/reports/index.html.haml
app/views/admin/venues/_form.html.haml
app/views/admin/venues/show.html.haml
app/views/commercials/edit.html.haml
app/views/commercials/new.html.haml
app/views/layouts/_admin_sidebar.html.haml
app/views/proposals/_form.html.haml
app/views/proposals/_tooltip.html.haml
spec/features/commercials_spec.rb
spec/features/info_desk_ability_spec.rb
spec/features/organization_admin_ability_spec.rb
spec/features/organizer_ability_spec.rb
spec/features/track_organizer_ability_spec.rb
spec/features/versions_spec.rb

This only replaces the UI facing wording. Specs will fail
as they have not been updated yet.

UI -- Repalce "Commerials" with "Materials".

---

Gemfile
Gemfile.lock
app/controllers/physical_tickets_controller.rb
app/models/commercial.rb
app/models/ticket_purchase.rb
app/views/conference_registrations/_form.html.haml
app/views/conferences/_tickets.haml
app/views/physical_tickets/index.html.haml
app/views/proposals/_proposal_form.html.haml
config/routes.rb

More fixes

---

app/assets/javascripts/osem-schedule.js
app/controllers/admin/rooms_controller.rb
app/controllers/application_controller.rb
app/helpers/conference_helper.rb
app/models/commercial.rb
app/views/admin/registrations/index.csv.haml
app/views/admin/rooms/_form.html.haml
app/views/admin/rooms/index.html.haml
app/views/conferences/_program.haml
app/views/conferences/_tickets.haml
app/views/devise/shared/_help.html.haml
app/views/devise/shared/_openid_links.html.haml
app/views/devise/shared/_sign_up_form_embedded.html.haml
app/views/layouts/_navigation.html.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/show.html.haml
app/views/shared/_media_item.html.haml
app/views/shared/_media_items.html.haml
config/database.yml
config/routes.rb
db/migrate/20200710215300_add_url_to_rooms.rb
db/schema.rb
lib/tasks/db.rake

* tweaks the navbar
* adds a URL field to Rooms
* uses a generic iframe fallback for OEmbed
* support apple pay verification for stripe
* fix the registrations CSV to not look for arrival times

Allow anything for materials, add URLs to Rooms

---

app/controllers/conferences_controller.rb
app/models/conference.rb
app/models/registration.rb
app/views/conferences/show.html.haml
app/views/layouts/application.html.haml

Show messages when users are not registered or have unpaid tickets.
Enforce that users have a registration ticket before registering.

Enforce ticket registrations

---

app/assets/stylesheets/osem.scss
app/controllers/admin/users_controller.rb
app/controllers/users_controller.rb
app/models/conference.rb
app/models/user.rb
app/uploaders/picture_uploader.rb
app/views/admin/conferences/_top_submitter.html.haml
app/views/admin/users/_form.html.haml
app/views/admin/users/show.html.haml
app/views/conference_registrations/show.html.haml
app/views/conferences/_highlights.haml
app/views/layouts/_navigation.html.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/_schedule_item.html.haml
app/views/users/edit.html.haml
app/views/users/show.html.haml
db/migrate/20200715034647_add_picture_to_users.rb
db/schema.rb

**Also:** fixes a small bug in delete event schedules.
* Uploaded photos take precedence over gravatar
* only basic forms for selecting size
* admins can now see and upload photos for users.
* TODO: deleting a photo.

Add Support for User-Uploaded Profile Pictures

---

app/assets/stylesheets/osem-navbar.scss
app/assets/stylesheets/osem.scss
app/controllers/admin/rooms_controller.rb
app/controllers/conference_registrations_controller.rb
app/helpers/events_helper.rb
app/models/event.rb
app/models/program.rb
app/models/registration.rb
app/models/room.rb
app/views/admin/rooms/_form.html.haml
app/views/admin/rooms/index.html.haml
app/views/conference_registrations/_event.html.haml
app/views/conference_registrations/_registration_info.html.haml
app/views/conferences/_program.haml
app/views/conferences/_tickets.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
db/migrate/20200716181602_add_order_to_rooms.rb
db/schema.rb

* Makes /events be the default schedule
* Adds an `order` field to rooms to force a specific ordering in the schedule
* Improve the navbar with custom profiles
* Fixes registering for specific events.
* Redesigns the interface for selecting which events to register for.
@bromagosa This is what things will look like when I deploy soon.

Improved Registration Flow, 

---

app/controllers/proposals_controller.rb
app/helpers/application_helper.rb
app/models/event.rb
app/models/event_user.rb
app/models/user.rb
app/views/conference_registrations/_registration_info.html.haml
app/views/proposals/_proposal_form.html.haml
app/views/proposals/_speaker_info.haml
app/views/proposals/_volunteer_info.haml
app/views/proposals/_volunteers_table.haml
app/views/proposals/index.html.haml
app/views/proposals/show.html.haml

Also fix a small bug for admin registrations edit.
IMPERECT:'
* there should be a real flag for can edit volunteers. Remove the method on `User`
Future TODO:
* deduced viewing pay for sessions
* prevent double-booking
* incorporate with attendance somehow.

Allow scheduling volunteers for sessions.

---

app/controllers/admin/events_controller.rb
app/helpers/application_helper.rb
app/models/user.rb
app/views/admin/events/_proposal.html.haml
app/views/admin/schedules/_form.html.haml
app/views/proposals/index.html.haml
app/views/schedules/_event.html.haml
app/views/tracks/show.html.haml

* Snap!ify the Schedule
* Volunteers w/o submissions can see their events

Improve Some Tracks Display, Fix Some VolunteersDisplays

---

app/controllers/schedules_controller.rb
app/controllers/users_controller.rb
app/helpers/events_helper.rb
app/models/ability.rb
app/models/event.rb
app/models/event_schedule.rb
app/views/schedules/_schedule_tabs.html.haml
app/views/schedules/happening_now.haml
config/routes.rb

Adds a tab to the Schedule view with events starting and ending in +- 30 minutes of the current time.
The logic seems OK but could be cleaned up.

Happening now

---

app/controllers/conference_registrations_controller.rb
app/helpers/application_helper.rb
app/models/registration.rb
app/models/user.rb
app/views/admin/commercials/index.html.haml
app/views/proposals/_form.html.haml
app/views/proposals/_proposal_form.html.haml
app/views/shared/_media_item.html.haml
config/initializers/devise.rb
spec/controllers/admin/conferences_controller_spec.rb
spec/features/cfp_ability_spec.rb
spec/features/commercials_spec.rb
spec/features/conference_spec.rb
spec/features/omniauth_spec.rb
spec/features/organization_admin_ability_spec.rb
spec/features/organizer_ability_spec.rb
spec/features/proposals_spec.rb
spec/features/splashpage_spec.rb
spec/features/ticket_purchases_spec.rb
spec/features/versions_spec.rb
spec/models/registration_spec.rb
spec/models/ticket_scanning_spec.rb
spec/models/user_spec.rb
spec/spec_helper.rb
spec/support/external_request.rb
spec/support/omniauth_macros.rb

Let's get Travis 🟢 🍏 📗 💚 🥗 
* Save RSpec progress inside tmp/ so you can use `only-failures`
* Fixes up tests, marks as pending when not critical.
```
👉 rspec spec/features --only-failures --fail-fast --seed 1 --order defined
```

Cleanup Test Cases

---

config/initializers/sentry.rb

No idea how useful this will be, but seems neat!

Add Sentry Pref Logging

---

Gemfile
Gemfile.lock
config/initializers/carrierwave.rb

Fix carrierwave

---

app/views/conferences/_conference_details.html.haml
app/views/conferences/index.html.haml

* Renders Markdown without escaping HTML
* shows all events by default
* TODO: Should filter by organization

Cleanup All Conference Index

---

app/controllers/admin/users_controller.rb
app/datatables/user_datatable.rb
app/views/admin/users/index.html.haml
app/views/admin/users/show.html.haml
spec/controllers/admin/users_controller_spec.rb
spec/datatables/user_datatable_spec.rb

* Admins can delete users from the user#show route
* Also include `confirmed?` status in the DataTables export. This is kinda hacky.

Admin delete users

---

app/controllers/admin/splashpages_controller.rb
app/controllers/conferences_controller.rb
app/helpers/application_helper.rb
app/helpers/conference_helper.rb
app/models/splashpage.rb
app/views/admin/splashpages/_form.html.haml
app/views/admin/splashpages/show.html.haml
app/views/conferences/_happening_now.haml
app/views/conferences/_header.haml
app/views/conferences/show.html.haml
spec/features/proposals_spec.rb
spec/features/splashpage_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/conference_helper_spec.rb

Adds a banner_photo input back to the splash page. 
Uses the conference picture in the navbar

Refactor splash image

---

app/views/conferences/_header.haml

- add check to ensure tickets are present
- add `current_user` to the caching.

fix the tickets check to show only when necessary

---

Gemfile
Gemfile.lock
config/routes.rb
db/schema.rb

setup pghero

---

.gitignore
app/assets/javascripts/fullcalendar.js.erb
app/controllers/admin/users_controller.rb
app/controllers/conference_registrations_controller.rb
app/controllers/schedules_controller.rb
app/controllers/users_controller.rb
app/jobs/mailbluster_create_lead_job.rb
app/jobs/mailbluster_edit_lead_job.rb
app/models/conference.rb
app/models/event.rb
app/models/program.rb
app/models/user.rb
app/services/full_calendar_formatter.rb
app/views/admin/users/_form.html.haml
app/views/layouts/_navigation.html.haml
app/views/layouts/application.html.haml
app/views/proposals/_toggle_favorite_event.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/events.html.haml
app/views/schedules/vertical_schedule.haml
app/views/users/edit.html.haml
config/database.yml
config/routes.rb
spec/features/proposals_spec.rb
spec/services/full_calendar_formatter_spec.rb

* fix admin user image upload
* fix css quote escaping
* fix room ordering on the vertical schedule page
* show the ylf2021 link
* personal schedule now includes speaking and volunteering events
* can favorite events from the events show page
* fix some bugs with the mail bluster callbacks

Pre-Snapcon fixes part 1 of many to come

---

app/assets/javascripts/osem-schedule.js
app/assets/stylesheets/osem-schedule.scss
app/models/event.rb
app/views/conferences/show.html.haml
app/views/layouts/application.html.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/events.html.haml
app/views/schedules/vertical_schedule.haml

* fix caching with the program data (hopefully)
* not the conference timezone
* improve clicking links to inyourtimezone
* fix a couple page titles

Some quick schedule enhancements.

---

app/controllers/proposals_controller.rb
app/controllers/schedules_controller.rb
app/helpers/events_helper.rb
app/models/program.rb
app/models/schedule.rb
app/views/proposals/_toggle_favorite_event.haml
app/views/schedules/_event.html.haml
app/views/schedules/events.html.haml
app/views/schedules/vertical_schedule.haml

Favorites / Caching Fixes

---

Gemfile
Gemfile.lock
config/routes.rb

So I can monitor background jobs

Add delayed job web interface

---

app/assets/javascripts/osem-schedule.js
app/controllers/schedules_controller.rb
app/helpers/events_helper.rb
app/models/event.rb
app/models/favourite_events.rb
app/views/proposals/_toggle_favorite_event.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/_event_types_key.haml
app/views/schedules/events.html.haml
app/views/schedules/happening_now.haml
app/views/schedules/show.haml

Schedule Perf / Favorites Fixes

---

app/assets/javascripts/fullcalendar.js.erb
app/views/schedules/show.haml

* Don't use full calendar's timezone display
* display it in the top of the page

Fixes 9 calendar

---

Procfile
app/controllers/proposals_controller.rb
app/helpers/events_helper.rb
app/models/ticket_purchase.rb
app/models/user.rb
app/views/conferences/_happening_now.haml
app/views/proposals/_toggle_favorite_event.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/events.html.haml
config/initializers/csp.rb
config/routes.rb
lib/tasks/cache.rb
spec/controllers/proposals_controller_spec.rb
spec/features/proposals_spec.rb

* sigh....fix caching/rendering of the stars for favoriting events in different views
* just don't query for event_favourities in any view other than proposls#show
* add the JS for setting favourite status to happening now partial
* Join event links! #182 -- track conference and event reg/attendane status
* Cleanup the favs view when no favs. Add some text. Fix bug when no events didn't shoe the nav bar.

T-Minus 2 Days Enhancements

---

app/models/room.rb

Sigh...too much caching makes this a mess...

Cache Busting After Room update

---

app/helpers/events_helper.rb

...yeesh...clearly this needs more testing.
-

Use the Join Event Route

---

.gitignore
app/controllers/proposals_controller.rb
app/helpers/events_helper.rb
app/models/conference.rb
app/models/event_schedule.rb
app/models/program.rb
app/models/room.rb
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/events.html.haml
app/views/schedules/happening_now.haml
spec/features/proposals_spec.rb

Better Join Links

---

app/assets/stylesheets/osem-schedule.scss
app/helpers/events_helper.rb
app/models/commercial.rb
app/models/event_schedule.rb
app/views/schedules/_event.html.haml
app/views/shared/_media_item.html.haml
app/views/shared/_media_items.html.haml

- re-enable slideshare, etc embeds
- tweak headings on the schedule
- re-enabled query memoization on the schedule

More Minor Fixes

---

app/controllers/conferences_controller.rb
app/models/event.rb
app/views/conferences/_conference_details.html.haml
app/views/conferences/index.html.haml

* try to cleanup styling 
* allow admins to create proposals in old conferences
* remove non-public events from the conferences index

Improvements to Conferences Index

---

Gemfile

Show user's timezone in the events views

---

app/assets/stylesheets/osem-schedule.scss
app/controllers/users_controller.rb
app/helpers/events_helper.rb
app/models/room.rb
app/serializers/room_serializer.rb
app/views/proposals/show.html.haml
app/views/schedules/_date_event_types.haml
app/views/schedules/_event_types_key.haml
app/views/schedules/events.html.haml
app/views/schedules/happening_now.haml
app/views/schedules/show.haml
app/views/users/edit.html.haml
db/migrate/20220426082022_add_discussion_url_to_rooms.rb
db/schema.rb
spec/factories/rooms.rb
spec/models/room_spec.rb
spec/serializers/room_serializer_spec.rb

* Cleanup the timezone implementation by a little bit
* refactor user profile page
* User profile: add selectize
* User profile: show the current browser timezone
* Event type labels: Simplify HTML structure
* Event type labels: reduce duplication, share partial
* Tidy up the instructions on the schedule pages
* Link to user profile on the schedule pages

Timezone Selection / View Enhancements

---

Gemfile.lock
app/controllers/schedules_controller.rb
app/controllers/tickets_controller.rb
app/models/user.rb
app/views/tickets/_ticket.html.haml
app/views/tickets/index.html.haml
spec/models/user_spec.rb

Restrict supports? check to only paid ticket purchases

---

app/views/schedules/_event.html.haml

sigh.... sigh...nil subevent fix.

---

app/assets/stylesheets/osem-schedule.scss
app/assets/stylesheets/osem.scss
app/models/event.rb
app/views/admin/schedules/show.html.haml
app/views/schedules/_event.html.haml
app/views/schedules/events.html.haml
app/views/schedules/show.haml

touch a parent event when editing

---

app/assets/javascripts/fullcalendar.js.erb
app/datatables/registration_datatable.rb
app/models/program.rb
app/services/full_calendar_formatter.rb
app/views/admin/registrations/index.html.haml
app/views/schedules/events.html.haml
spec/services/full_calendar_formatter_spec.rb

* Calendar Spacing
* add tickets to reg table
* caching / schedule / navbar tweaks
**Checklist**
-

Minor Enhancements

---

app/datatables/registration_datatable.rb

fix registrations filtering

---

app/models/event.rb
app/views/admin/reports/_missing_speakers.html.haml
app/views/admin/reports/index.html.haml
app/views/proposals/show.html.haml
app/views/schedules/_event.html.haml

**Checklist**

---

app/controllers/admin/rooms_controller.rb
app/helpers/events_helper.rb
app/models/event.rb
app/models/event_schedule.rb
app/views/schedules/_event.html.haml

Trim Rooms fields, tweak join links displays

---

app/models/room.rb
app/views/admin/rooms/_form.html.haml
app/views/admin/rooms/index.html.haml
app/views/layouts/application.html.haml
app/views/rooms/live_session.html.haml

**Improvements to the Live Sessions View**
* fix the CSS a bit to reduce content / gaps
* fix the Rooms#edit for after v7 update w/ bootstrap classes
* show meeting/discussion URLs on the rooms#index table
* add a method to convert a zoom Join URL to a browser URL for a meeting

Enhance Rooms / Live Session Page

---

config/database.yml

this will reduce config/install issues.
Uses the $USER variable when set.
**Checklist**
-
-

Make the db config use the local user.

---

app/controllers/proposals_controller.rb
app/models/program.rb

ensure @superevents is set on proposals controller

---

app/views/proposals/new.html.haml

Ensure user selectize works on proposal#new

---

app/helpers/events_helper.rb
app/models/program.rb
app/views/proposals/_form.html.haml
app/views/proposals/_submission_type_content_form.haml

- ugh, fix typo
- yet more cleanup of the proposals form
**Checklist**
-
-

Impovements/Fix to Events Proposals

---

app/helpers/application_helper.rb
app/views/conferences/_lodging.haml
app/views/layouts/_navigation.html.haml
app/views/layouts/_snapcon_nav.haml

Misc Cleanup of code
- reduce N+1 queries in generating nav bar
- cleanup a bunch of partials
- remove some ugly icons

Cleanup sidebar queries

---

app/views/conferences/_call_for_content.haml
app/views/conferences/_program.haml
app/views/conferences/_registration.haml
app/views/conferences/_venue.haml

Reduce navbar links

---

app/assets/stylesheets/osem.scss
app/helpers/events_helper.rb
app/models/event_schedule.rb
app/views/admin/conferences/_form_fields.html.haml
app/views/admin/event_types/_form.html.haml
app/views/proposals/_form.html.haml
app/views/proposals/show.html.haml
app/views/rooms/live_session.html.haml
app/views/schedules/_event.html.haml

lower happening now threshold to 15 minutes

---

app/controllers/users_controller.rb
app/models/user.rb

Filter private usernames in selectize functions
